############# English navigation ##############

# main menu

[[main]]
name = "home"
url = ""
weight = 1

[[main]]
name = "about"
url = "about/"
weight = 2

[[main]]
name = "publications"
url = "publications/"
weight = 3

[[main]]
name = "activities"
url = "activities/"
weight = 4

[[main]]
name = "awards"
url = "awards/"
weight = 5

[[main]]
name = "contact"
url = "contact/"
weight = 6

# dropdown menu
[[main]]
name = "Blogs"
weight = 7
hasChildren = true

  # dropdown item
  [[main]]
  parent = "Blogs"
  name = "Front-End"
  url = "/blog/how_to_create_hugo_contact_form_with_google_forms"

  [[main]]
  parent = "Blogs"
  name = "page 2"
  url = "/"
